-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. Consumption History
-- Stores hourly energy usage data for patterns/forecasting
create table if not exists consumption_history (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references auth.users(id) on delete cascade not null, -- Assumes Supabase Auth. Use 'users(id)' if using custom table.
  -- user_id uuid references users(id) on delete cascade not null, -- UNCOMMENT THIS LINE if using custom 'users' table
  timestamp timestamptz not null default now(),
  hourly_consumption float not null, -- In Wh
  day_of_week int not null, -- 0-6
  hour_of_day int not null, -- 0-23
  temperature float, -- Degrees Celsius
  created_at timestamptz default now()
);

create index if not exists idx_history_user_time on consumption_history(user_id, timestamp);

-- 2. Baseline Statistics
-- Stores calculated statistical baselines (mean, stdDev) per hour for anomaly detection
create table if not exists baseline_statistics (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid not null, -- Foreign key logic handled in app if using custom table
  hour int not null check (hour >= 0 and hour <= 23),
  mean float not null default 0,
  std_dev float not null default 0,
  min_val float not null default 0,
  max_val float not null default 0,
  data_points int not null default 0,
  threshold_multiplier float not null default 2.0,
  last_updated timestamptz default now(),
  unique(user_id, hour)
);

-- 3. Anomaly Events
-- Stores detected anomalies
create table if not exists anomaly_events (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid not null,
  timestamp timestamptz not null default now(),
  hour_of_day int not null,
  consumption float not null,
  expected_mean float not null,
  expected_std_dev float not null,
  z_score float not null,
  confidence text check (confidence in ('high', 'medium', 'low', 'none')),
  deviation text,
  deviation_percent float,
  possible_cause text,
  recommendation text,
  estimated_extra_cost float,
  status text default 'detected', -- detected, acknowledged, false_positive
  user_feedback jsonb, -- Stores { appliance, wasNormal, etc. }
  created_at timestamptz default now()
);

-- 4. User Feedback
-- Tracks feedback to improve ML thresholds
create table if not exists user_feedback (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid not null,
  hour int not null,
  pattern_type text not null, -- 'spike' or 'dip'
  feedback_type text not null, -- 'normal' or 'problem'
  appliance text,
  occurrences int default 1,
  adjusted_threshold float not null,
  last_occurrence timestamptz default now(),
  created_at timestamptz default now()
);

-- 5. Peak Hour Settings
-- Configuring tariffs and peak hours for user
create table if not exists peak_hour_settings (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid unique not null,
  user_state text not null,
  user_discount_flag boolean default false,
  monthly_subsidy_units float default 100,
  peak_hours jsonb not null default '[]', -- Array of {start, end, rate}
  off_peak_hours jsonb not null default '[]',
  updated_at timestamptz default now()
);

-- 6. Notification Settings
create table if not exists notification_settings (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid unique not null,
  email_notifications boolean default true,
  sms_notifications boolean default false,
  push_notifications boolean default true,
  anomaly_alerts boolean default true,
  weekly_reports boolean default true,
  email_address text,
  phone_number text,
  updated_at timestamptz default now()
);

-- 7. Notification Logs
create table if not exists notification_logs (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid not null,
  anomaly_id uuid references anomaly_events(id),
  type text not null, -- email, sms, push
  recipient text,
  message text,
  status text, -- sent, failed, clicked
  sent_at timestamptz default now(),
  clicked_at timestamptz
);

-- 8. Energy Readings (Already existed, but ensuring structure if missing)
create table if not exists energy_readings (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  voltage float,
  current float,
  power float,
  energy_kwh float,
  cost_rs float,
  device text -- references user_id in context of hardware
);

-- Row Level Security (RLS) Policies (Optional but Recommended)
-- alter table consumption_history enable row level security;
-- create policy "Users can view own data" on consumption_history for select using (auth.uid() = user_id);

-- 9. Additions for Enhanced Data (PF & Frequency)
-- Run this if your table already exists
alter table energy_readings add column if not exists pf float default 0.95;
alter table energy_readings add column if not exists frequency float default 50.0;
